name: Release Flow

on:
  release:
    types: [prereleased, released]

jobs:
  test_envs:
    name: test_envs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    environment: ${{ github.ref == 'released' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Print hello
        run: |
            echo ${{ vars.HELLO }}