name: Release Flow

on:
  release:
    types: [prereleased, released]

jobs:
  production_deployment:
    if: endsWith(github.event.release.name, '(prod)')
    name: To production
    environment: production
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Print env_name
        run: |
          echo $ENV_NAME
  staging_deployment:
    if: endsWith(github.event.release.name, '(staging)')
    name: To staging
    environment: staging
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Print env_name
        run: |
          echo $ENV_NAME
  shorts_deployment:
    if: endsWith(github.event.release.name, '(shorts)')
    name: To shorts
    environment: shorts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Print env_name
        run: |
          echo $ENV_NAME

